### PR TITLE
[WIP] Feature/viewmap

### PR DESCRIPTION
**Pull request by edbrett**

### CODE REVIEW

**Comment by davidsingal** [comment]
@edbrett could you fix conflicts please?

**Comment by nerik** [comment]
@davidsingal, it's a WIP branch, maybe we can wait for @edbrett to finish and then resolve conflicts?

**Comment by davidsingal** [comment]
Ok, in this case I prefer not to make a PR and wait until this feature is ready.

**Comment by nerik** [comment]
Ok. I find having PRs open unfinished features useful, to discuss code if needed (especially with beginners), but I reckon that's more the exception than the rule.

**Comment by davidsingal** [comment]
I agree but only when we really need it.

**Comment by nerik** [comment]
👍

**Pull request closed without merging**
